# Generated by Django 3.2.6 on 2021-12-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kabak', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='duration',
            field=models.TimeField(default='0:00', verbose_name='Продолжительность'),
            preserve_default=False,
        ),
    ]
