# Generated by Django 3.2.6 on 2021-12-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kabak', '0002_reservation_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrs', verbose_name='QR code'),
        ),
    ]
